### ISSUE TITLE
Can it be automatically injected into the `<head>` of HTML like `.css`?

### ISSUE THREAD

**Issue by nanarino** [kitschpatrol/vite-plugin-iife#1]
[document](https://vitejs.dev/guide/features.html#disabling-css-injection-into-the-page)

```ts
import './foo.css' // will be injected into the page
import otherStyles from './bar.css?inline' // will not be injected

// Load Web Workers
import Worker from './worker.js?worker'
// Web Workers inlined as base64 strings at build time
import InlineWorker from './worker.js?worker&inline'
```

I envision using `?iife` to inject automatically;  `?iife&raw` to inject and not compile; `?iife&inline` to do the same as it currently does; in version 2.0

**Comment by kitschpatrol** [comment]
Thanks for the suggestion.

This could be convenient, but because `?iife` is used with with TypeScript / JavaScript files, I prefer to keep the behavior close to how Vite handles regular `.ts` and `.js` imports, which are _not_ auto-injected like `.css` imports.
